
okta:
  oauth2:
    issuer: https://dev-61851708.okta.com/oauth2/default
    clientId: 0oa5s4s4vkpSMjGtQ5d7
    rolesClaim: groups
app:
  cors:
    allowed-origins: "*"
  number-of-fake-jobs: 100

logging:
  level:
    org.springframework.data.elasticsearch.core: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.security: DEBUG

spring:
  application:
    name: api-gateway-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://host.docker.internal:8761/eureka}
  instance:
    preferIpAddress: true
zuul:
  sensitive-headers:
  routes:
    eauction-query:
      path: /eauction-query/**
      url: http://host.docker.internal:8081/
    eauction-command:
      path: /eauction-command/**
      url: http://host.docker.internal:8082/
  host:
    socket-timeout-millis: 30000