server:
  port: 8081
  forward-headers-strategy: framework
spring:
  application:
    name: eauction-query
  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      database: prodcut-bid
  kafka:
    bootstrap-servers:
      - kafka:9092
    consumer:
      group-id: group-id
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.LongDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
okta:
  oauth2:
    issuer: https://dev-61851708.okta.com/oauth2/default
    audience: api://default
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://host.docker.internal:8761/eureka}