FROM openjdk:11-jdk-slim
MAINTAINER Taner Diler <taner.diler@gmail.com>
ADD target/eauction-command-0.0.1-SNAPSHOT.jar eauction-command-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/eauction-command-0.0.1-SNAPSHOT.jar"]
EXPOSE 8082